syntax = "proto3";

package analytics;

option go_package = "analytics-service/proto/analytics";

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

service AnalyticsService {
  rpc RecordEvent(RecordEventRequest) returns (google.protobuf.Empty);
}

enum EventStatus {
  STATUS_UNKNOWN = 0;
  STATUS_SUCCESS = 1;
  STATUS_FAILURE = 2;
}

message RecordEventRequest {
  string      event_type   = 1;
  EventStatus status       = 2;
  string      error_code   = 3;
  string      user_id      = 4;
  string      ip           = 5;
  google.protobuf.Timestamp occurred_at = 6;
}


